log:
  log_freq: 8
  exp_dir: train_logs/3dmatch

model:
  num_layers: 4
  in_points_dim: 3
  first_feats_dim: 128
  final_feats_dim: 32
  first_subsampling_dl: 0.025
  in_feats_dim: 1
  conv_radius: 2.5
  deform_radius: 5.0
  num_kernel_points: 15
  KP_extent: 2.0
  KP_influence: linear
  aggregation_mode: sum
  fixed_kernel_points: center
  use_batch_norm: True
  batch_norm_momentum: 0.02

overlap_attention_module:
  gnn_feats_dim: 256
  dgcnn_k: 10
  num_head: 4
  ppf_k: 64
  radius_mul: 32
  bottleneck: False
  nets: ['gge','cross_attn','gge']

loss:
  pos_margin: 0.1
  neg_margin: 1.4
  log_scale: 16
  pos_radius: 0.0375
  safe_radius: 0.1
  overlap_radius: 0.0375
  matchability_radius: 0.05
  w_circle_loss: 1.0
  w_overlap_loss: 1.0
  w_saliency_loss: 0.0
  max_points: 256

optimiser:
  optimizer: SGD
  max_epoch: 40
  lr: 0.005
  weight_decay: 0.000001
  momentum: 0.98
  scheduler: ExpLR
  T_0: 10
  T_mult: 4
  eta_min: 0.00001
  scheduler_gamma: 0.95
  scheduler_freq: 1
  iter_size: 1

dataset:
  dataset: threedmatch
  benchmark: 3DMatch
  root: Datasets/indoor
  batch_size: 1
  num_workers: 6
  augment_noise: 0.005
  train_info: configs/indoor/train_info.pkl
  val_info: configs/indoor/val_info.pkl
